contact_links:
  - name: Lounge Chat
    url: https://read-me.pro/invite/4HrJrbTE
    about: Ask questions and discuss with others.
  - name: Discussions
    url: https://landing.read-me.pro/
    about: For larger feature requests and general question & answer.
